version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=oefenroosterDebug
    ports:
      - 54322:5432
    volumes: 
      - C:/Users/drooge50/Documents/DataDrogeCode:/var/lib/postgresql/data
  drogecode.knrm.oefenrooster.server:
    image: kanman/drogecode.knrm.oefenrooster:latest
    restart: always
    environment:
      - ConnectionStrings__postgresDB=host=host.docker.internal;port=54322;database=BackupProd;username=postgresUser;password=postgresPW
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    ports:
        - 6080:80
        - 6443:443