version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    ports:
      - '5432:5432'
    volumes: 
      - D:/programming/dockerData/postgres-data:/var/lib/postgresql/data
  drogecode.knrm.oefenrooster.server:
    image: kanman/drogecode.knrm.oefenrooster:0.0.3
    restart: always
    environment:
      - ConnectionStrings__postgresDB=host=host.docker.internal;port=5432;database=postgresDB;username=postgresUser;password=postgresPW
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    ports:
        - 6080:80
        - 6443:443