//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogecode.Knrm.Oefenrooster.Client.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateRequired_nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateRequired_nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drogecode.Knrm.Oefenrooster.Client.Resources.Pages.UpdateRequired.nl-NL", typeof(UpdateRequired_nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik [ctrl]+[shift]+[R].
        /// </summary>
        internal static string Click__ctrl___shift___R_ {
            get {
                return ResourceManager.GetString("Click [ctrl]+[shift]+[R]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik op onderstaande knop om de nieuwe versie van de app te laden..
        /// </summary>
        internal static string Click_the_button_below_to_load_the_new_version_of_this_app {
            get {
                return ResourceManager.GetString("Click the button below to load the new version of this app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force close de app en wacht een minuut alvorens de app weer te openen.
        /// </summary>
        internal static string Force_close_the_app_and_wait_a_minute__reopen_app {
            get {
                return ResourceManager.GetString("Force close the app and wait a minute, reopen app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als herladen niet werkt.
        /// </summary>
        internal static string If_reloading_doesn_t_work {
            get {
                return ResourceManager.GetString("If reloading doesn\'t work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herladen.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smartphone.
        /// </summary>
        internal static string Smartphone {
            get {
                return ResourceManager.GetString("Smartphone", resourceCulture);
            }
        }
    }
}
