//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogecode.Knrm.Oefenrooster.Client.Resources.Pages.Configuration.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserRolesList_nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRolesList_nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drogecode.Knrm.Oefenrooster.Client.Resources.Pages.Configuration.Components.UserR" +
                            "olesList.nl-NL", typeof(UserRolesList_nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene toegang.
        /// </summary>
        internal static string basic_access {
            get {
                return ResourceManager.GetString("basic_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene toegang nodig voor algemen toegang tot deze applicatie.
        /// </summary>
        internal static string basic_access_body {
            get {
                return ResourceManager.GetString("basic_access-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene instellingen.
        /// </summary>
        internal static string configure_global_all {
            get {
                return ResourceManager.GetString("configure_global_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegang tot algemene instellingen pagina.
        /// </summary>
        internal static string configure_global_all_body {
            get {
                return ResourceManager.GetString("configure_global_all-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer training targets.
        /// </summary>
        internal static string configure_training_target {
            get {
                return ResourceManager.GetString("configure_training_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegang tot pagina om training targets te configureren.
        /// </summary>
        internal static string configure_training_target_body {
            get {
                return ResourceManager.GetString("configure_training_target-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configureer training types.
        /// </summary>
        internal static string configure_training_types {
            get {
                return ResourceManager.GetString("configure_training-types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegang tot instellingen pagina voor training types.
        /// </summary>
        internal static string configure_training_types_body {
            get {
                return ResourceManager.GetString("configure_training-types-body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern ID.
        /// </summary>
        internal static string ExternalId {
            get {
                return ResourceManager.GetString("ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        internal static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon © footer.
        /// </summary>
        internal static string showCfooter {
            get {
                return ResourceManager.GetString("showCfooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon © footer onder iedere pagina.
        /// </summary>
        internal static string showCfooter_body {
            get {
                return ResourceManager.GetString("showCfooter-body", resourceCulture);
            }
        }
    }
}
