# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  drogecode.knrm.oefenrooster.server:
    build:
      context: "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster"
      dockerfile: "src/Server/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Drogecode.Knrm.Oefenrooster.Server.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "kanman/drogecode.knrm.oefenrooster:dev"
    ports:
    - "127.0.0.1:57010:57100"
    - "127.0.0.1:57210:57300"
    volumes:
    - "C:\\Users\\Taco\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster\\src\\Server:/app:rw"
    - "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster:/src:rw"
    - "C:\\Users\\Taco\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\Taco\\AppData\\Local\\JetBrains\\Installations\\Rider233\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Taco\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_4_06_14_56_17:/var/opt/rider-debugger:rw"
    working_dir: "/app"
