# This is a generated file. Not intended for manual editing.
services:
  drogecode.knrm.oefenrooster.server:
    build:
      context: "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster"
      dockerfile: "src/Server/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Drogecode.Knrm.Oefenrooster.Server.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "kanman/drogecode.knrm.oefenrooster:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster\\src\\Server:/app:rw"
    - "C:\\Users\\Taco\\source\\repos\\Drogecode.Knrm.Oefenrooster:/src:rw"
    - "C:\\Users\\Taco\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Users\\Taco\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3\\Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\Taco\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Taco\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_11_13_18_37_04:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
