//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogecode.Knrm.Oefenrooster.Client.Resources.Pages.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultConfig_nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultConfig_nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drogecode.Knrm.Oefenrooster.Client.Resources.Pages.Configuration.DefaultConfig.nl" +
                            "-NL", typeof(DefaultConfig_nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak nieuw standaard rooster aan.
        /// </summary>
        internal static string Add_new_default_schedule {
            get {
                return ResourceManager.GetString("Add new default schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig standaard rooster.
        /// </summary>
        internal static string Edit_default_schedule {
            get {
                return ResourceManager.GetString("Edit default schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen waarde voor begin datum.
        /// </summary>
        internal static string No_value_for_start_date {
            get {
                return ResourceManager.GetString("No value for start date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen waarde voor eind datum.
        /// </summary>
        internal static string No_value_for_till_date {
            get {
                return ResourceManager.GetString("No value for till date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgorde.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw standaard rooster.
        /// </summary>
        internal static string Put_default_schedule {
            get {
                return ResourceManager.GetString("Put default schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag niet voor begin datum.
        /// </summary>
        internal static string Should_not_be_before_start_date {
            get {
                return ResourceManager.GetString("Should not be before start date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mag niet in het verleden.
        /// </summary>
        internal static string Should_not_be_in_the_past {
            get {
                return ResourceManager.GetString("Should not be in the past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eind tijd.
        /// </summary>
        internal static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tijd.
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geldig vanaf.
        /// </summary>
        internal static string Valid_from {
            get {
                return ResourceManager.GetString("Valid from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geldig tot.
        /// </summary>
        internal static string Valid_untill {
            get {
                return ResourceManager.GetString("Valid untill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekdag.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
    }
}
