name: Publish Docker image
permissions:
  contents: read

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Test, build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    env:
      Playwright:BaseUrl: ${{ secrets.playwright_BaseUrl }}
      Playwright:Users:Basic:Name: ${{ secrets.playwright_Users_Basic_Name }}
      Playwright:Users:Basic:Password: ${{ secrets.playwright_Users_Basic_Password }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: dotnet restore ./Drogecode.Knrm.Oefenrooster.sln

      - name: Build
        run: dotnet build ./src/Server/Drogecode.Knrm.Oefenrooster.Server.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Drogecode.Knrm.Oefenrooster.GitHubActionTests.sln --configuration Release --no-restore
        
      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1

      - name: replace
        uses: cschleiden/replace-tokens@4d5a042c84c3568b3858b7af9394923d2d5195c9 #v1.3
        with:
            files: '["**/index.html","**/version.js","**/DefaultSettingsHelper.cs"]'
        env:
            VERSION_TOKEN: ${{ steps.get_version.outputs.VERSION }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          file: ./src/Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/drogecode.knrm.oefenrooster:${{ steps.get_version.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
