name: Publish Docker image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Test, build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Install dependencies
        run: dotnet restore ./Drogecode.Knrm.Oefenrooster.sln

      - name: Build
        run: dotnet build ./src/Server/Drogecode.Knrm.Oefenrooster.Server.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./Drogecode.Knrm.Oefenrooster.sln --configuration Release --no-restore
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: replace
        uses: cschleiden/replace-tokens@v1
        with:
            files: '["**/index.html","**/version.js","**/DefaultSettingsHelper.cs"]'
        env:
            VERSION_TOKEN: ${{ steps.get_version.outputs.VERSION }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./src/Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/drogecode.knrm.oefenrooster:${{ steps.get_version.outputs.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
