name: On push
permissions:
  contents: read
  pull-requests: write

on: 
    push:
        branches:
        - '**'
        tags-ignore:
        - '**'
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.53.0-noble
    env:
      Playwright:BaseUrl: ${{ secrets.playwright_BaseUrl }}
      Playwright:Users:Basic:Name: ${{ secrets.playwright_Users_Basic_Name }}
      Playwright:Users:Basic:Password: ${{ secrets.playwright_Users_Basic_Password }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./Drogecode.Knrm.Oefenrooster.sln
      - name: Build
        run: dotnet build ./Drogecode.Knrm.Oefenrooster.sln --configuration Release --no-restore
      - name: Run tests
        run: |
          mkdir -p ./tests/Drogecode.Knrm.Oefenrooster.Playwright/bin/Release/net9.0/playwright-debug
          dotnet test ./Drogecode.Knrm.Oefenrooster.sln \
            --configuration Release \
            --no-restore \
            --logger "trx;LogFileName=test_results.trx" \
            --results-directory ./tests/Drogecode.Knrm.Oefenrooster.Playwright/bin/Release/net9.0/playwright-debug
      - name: Upload Playwright debug artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-debug
          path: ./tests/Drogecode.Knrm.Oefenrooster.Playwright/bin/Release/net9.0/playwright-debug