name: On push
permissions:
  contents: read
  pull-requests: write

on: 
    push:
        branches:
        - '**'
        tags-ignore:
        - '**'
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
    env:
      Playwright:BaseUrl: ${{ secrets.playwright_BaseUrl }}
      Playwright:Users:Basic:Name: ${{ secrets.playwright_Users_Basic_Name }}
      Playwright:Users:Basic:Password: ${{ secrets.playwright_Users_Basic_Password }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install dependencies
        run: dotnet restore ./Drogecode.Knrm.Oefenrooster.sln
      - name: Build
        run: dotnet build ./src/Server/Drogecode.Knrm.Oefenrooster.Server.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./Drogecode.Knrm.Oefenrooster.sln --configuration Release --no-restore
