name: On push

on: 
    push:
        branches:
        - '**'
        tags-ignore:
        - '**'
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore ./Drogecode.Knrm.Oefenrooster.sln
      - name: Install coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Build
        run: dotnet build ./src/Server/Drogecode.Knrm.Oefenrooster.Server.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test ./Drogecode.Knrm.Oefenrooster.sln --configuration Release --no-restore
      - name: coverage
        run: dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'
